-- Basic config
require("core.configs")
require("core.highlights")
require("core.mappings")
require("core.plugins")
require("core.colors")

-- Plugins
require("plugins.autopairs")
require("plugins.buffline")
require("plugins.cmp")
require("plugins.git")
require("plugins.gitsigns")
require("plugins.lspconfig")
require("plugins.lspkind")
require("plugins.lspsaga")
require("plugins.lualine")
require("plugins.mason")
require("plugins.neotree")
require("plugins.nullls")
require("plugins.telescope")
require("plugins.toggleterm")
require("plugins.treesitter")
require("plugins.ts-autotag")
require("plugins.ufo")
require("plugins.whichkey")
