-- Basic config
require("core.configs")
require("core.highlights")
require("core.mappings")
require("core.plugins")
require("core.colors")

-- Plugins
require("plugins.neotree")
require("plugins.whichkey")
require("plugins.autopairs")
require("plugins.bufferline")
require("plugins.cmp")
require("plugins.colorizer")
require("plugins.comment")
require("plugins.git")
require("plugins.gitsigns")
require("plugins.lsp-colors")
require("plugins.lspkind")
require("plugins.lualine")
require("plugins.neosolarized")
require("plugins.telescope")
require("plugins.treesitter")
require("plugins.ts-autotag")
require("plugins.web-devicons")
require("plugins.ufo")
require("plugins.toggleterm")


require("plugins.mason")
require("plugins.lspconfig")
require("plugins.lspsaga")
require("plugins.null-ls")
